title = "Xi Lin"
baseURL = "https://profile.erix025.me/"
theme = "erix-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Hangzhou, Zhejiang"
email = "erix025@outlook.com"
favicon = "/favicon.ico"
firstName = "Xi"
lastName = "Lin"
chineseName = "林熙"
phone = "1-555-555-1234"
profileImage = "img/avatar.png"
showQr = false
showContact = false
showBoards  = false
showCertifications = false
showSocializations = true
blogUrl = "https://blogs.erix025.me"
sections = ["news","publications","experience","awards","education","blog"]

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/erix025/"

[[params.handles]]
    name = "X"
    link = "https://x.com/erix035"
    icon = "x-twitter"

[[params.handles]]
    name = "Email"
    link = "mailto:erix025@outlook.com"
    icon = "envelope"
    iconClass = "fas"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/xi-lin-482a1b393/"
    
[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"